language: node_js
node_js:
- '0.12'
- '0.10'
script:
- npm run test
after_script:
- 'npm install codeclimate-test-reporter && cat coverage/lcov.info | codeclimate-test-reporter'
CODECLIMATE_REPO_TOKEN=8ed5a59ed0bc2804509068de17ed8e29ac30c5d7a4406315e7cc05e3cda9b2e3:
  secure: ZpJ8ltSqrsM+d19q5xMIZW3fGtiBovaEupTcw9u/HOQdgzyPtcVqEMIl6BOCRxuj7Ca+R9lB0aEQbRFnz1DHVTvUttgCPGbVDxbct0Ela2E51dEjHw918SOutm+JCKsOzyLHXf1bBdI2nTNgndZvM7kbZNnnSfUQk0/vw2usuY/im3WdFZw1BKKJNJTZLNTF55IOQLq1X7Kzt12gTHSk+03hVgPqhnRxjoY5/5Zq6hwg3lFQdkAILtPz82HhfIWY7/XuPV55gefUAvyXSAoBwzynCOxX7aa3v0FynPcdQCIoajaeWSdrrj7wTYiQYV1Ll20EgTjAtbIxcUyls4zZf4NhU7MozvZ27Bw3oThzcOjk7eNMeqc6BtmU8ApEzAnCDfuUZubdLK4S60y5Pi2ORJ+n6Popxi42PA+6fuLoaA2sJ6BxMLkNpT5EqfVfmuYDuTMuqyFflatCSmCMaDLwIHBwATadIuGwfcjuARbV8JxnNw3gs7J3Bu+GwSbe7MUvcspjaDvxoAtP0FZU2Gk8qVHdkviQu535mxEAQeH2v/BVTvqx1o+YnCV6yotGGsHezENnzR5vvCDiuqaehBZ9i1z6Q8xorO0MXZOa/Cjl/7UQznHWjZqkvw4fYSSV8OPy68h8RaBX85Vi7k0T6pDGRgMl1V6qWtP6tbXMDmuVXnY=
